project: default
destination:
  server: https://kubernetes.default.svc
  namespace: cert-manager
syncPolicy:
  syncOptions:
    - CreateNamespace=true
sources:
  - repoURL: https://charts.jetstack.io
    targetRevision: v1.16.2
    helm:
      valueFiles:
        - $values/cert-manager/values.yaml
    chart: cert-manager
  - repoURL: https://github.com/lumos-run/apps.git
    targetRevision: main
    ref: values
